
package prozhe2;

import java.awt.event.ActionEvent;
import java.util.Objects;


public class Signupmenuu extends javax.swing.JFrame {

   
    public Signupmenuu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernamefeild = new javax.swing.JTextField();
        passwordfeild = new javax.swing.JPasswordField();
        Signupbutton = new javax.swing.JButton();
        menubutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("UserName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 50));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 50));

        usernamefeild.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        getContentPane().add(usernamefeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 30));
        getContentPane().add(passwordfeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, 30));

        Signupbutton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Signupbutton.setForeground(new java.awt.Color(255, 255, 0));
        Signupbutton.setText("Sign Up");
        Signupbutton.setContentAreaFilled(false);
        Signupbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(Signupbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, 50));

        menubutton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        menubutton.setForeground(new java.awt.Color(153, 0, 0));
        menubutton.setText("Back to menu");
        menubutton.setContentAreaFilled(false);
        menubutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menubuttonMouseClicked(evt);
            }
        });
        getContentPane().add(menubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prozhe2/images/green-eye-cyber-circuit-future-technology-concept-background_42077-1930.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menubuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubuttonMouseClicked
         menubutton.addActionListener((ActionEvent e) -> {
               setVisible(false);
               Mainmenu a = new Mainmenu();
               a.setVisible(true);
           });
    }//GEN-LAST:event_menubuttonMouseClicked

    private void SignupbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupbuttonMouseClicked
           Signupbutton.addActionListener((ActionEvent e) -> {
                 User user = new User(usernamefeild.getText(),passwordfeild.getPassword() );
                 System.out.println(user);
                 
                 Database.insertIntoUser(user);
                 
                 
             });
                          Signupbutton.addActionListener((ActionEvent e) -> {

                             this.dispose();
                              inMenu menu = new inMenu();
                              menu.setVisible(true);
                              
                              
       }); 
    }//GEN-LAST:event_SignupbuttonMouseClicked

     @Override
    public boolean equals(Object object) {
        if (this == object) return true;
        if (!(object instanceof User)) return false;
        if (!super.equals(object)) return false;
        User user = (User) object;
        return this.hashCode() == user.hashCode();
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), passwordfeild);
    }

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signupmenuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signupmenuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signupmenuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signupmenuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signupmenuu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Signupbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menubutton;
    private javax.swing.JPasswordField passwordfeild;
    private javax.swing.JTextField usernamefeild;
    // End of variables declaration//GEN-END:variables
}
